### ISSUE TITLE
CI builds

### ISSUE THREAD

**Issue by kbremner** [neuecc/LINQ-to-BigQuery#50]
AppVeyor offers a free CI service for open-source .NET projects. This should be set up for this project to check that all tests pass for a PR before merging. This can only be set up by the owner of the project or a collaborator. See:
http://www.appveyor.com/

**Comment by kbremner** [comment]
These are the settings we use to build the project on AppVeyor:

```
version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore BigQuery.Linq.sln
build:
  verbosity: minimal
```

If you put that in to a file in the root of the solution called "appveyor.yml" then AppVeyor will pick up those settings.

Hope that helps!
